In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.utils import np_utils
from keras.layers.core import Dense, Activation, Dropout

**Lendo os Dados**

In [0]:
train = pd.read_csv('/content/drive/My Drive/datasets/fashionmnist/fashion-mnist_train.csv')

In [0]:
train.head()

label  pixel1  pixel2  pixel3  ...  pixel781  pixel782  pixel783  pixel784
0      2       0       0       0  ...         0         0         0         0
1      9       0       0       0  ...         0         0         0         0
2      6       0       0       0  ...         0         0         0         0
3      0       0       0       0  ...         0         0         0         0
4      3       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [0]:
train.shape

(60000, 785)

In [0]:
labels = train.ix[:, 0].values.astype('int32')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [0]:
labels

array([2, 9, 6, ..., 8, 8, 7], dtype=int32)

In [0]:
labels.shape

(60000,)

In [0]:
X_train = (train.ix[:, 1:].values).astype('float32')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:822: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)


In [0]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
X_train.shape

(60000, 784)

In [0]:
X_test = pd.read_csv('/content/drive/My Drive/datasets/fashionmnist/fashion-mnist_test.csv')

In [0]:
X_test.head()

label  pixel1  pixel2  pixel3  ...  pixel781  pixel782  pixel783  pixel784
0      0       0       0       0  ...         0         0         0         0
1      1       0       0       0  ...         0         0         0         0
2      2       0       0       0  ...        31         0         0         0
3      2       0       0       0  ...       222        56         0         0
4      3       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [0]:
labels_test = X_test.iloc[:, 0]

In [0]:
labels_test.shape

(10000,)

In [0]:
X_test.drop(labels=['label'], axis=1, inplace=True)

In [0]:
X_test.head()

pixel1  pixel2  pixel3  pixel4  ...  pixel781  pixel782  pixel783  pixel784
0       0       0       0       0  ...         0         0         0         0
1       0       0       0       0  ...         0         0         0         0
2       0       0       0       0  ...        31         0         0         0
3       0       0       0       0  ...       222        56         0         0
4       0       0       0       0  ...         0         0         0         0

[5 rows x 784 columns]

In [0]:
X_test = X_test.values.astype('float32')

In [0]:
X_test.shape

(10000, 784)

**Convertendo lista de labels para matriz de class binária**

In [0]:
y_train = np_utils.to_categorical(labels)

In [0]:
y_train

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [0]:
y_train.shape

(60000, 10)

**Pré-processamento: dividir pelo máximo e subtrair da média**

In [0]:
scale = np.max(X_train)

In [0]:
scale

255.0

In [0]:
X_train /= scale

In [0]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
X_test /= scale

In [0]:
X_test

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.00392157,
        0.        ],
       [0.        , 0.00392157, 0.01176471, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [0]:
mean = np.std(X_train)

In [0]:
mean

0.3528113

In [0]:
X_train -= mean

In [0]:
X_train

array([[-0.3528113, -0.3528113, -0.3528113, ..., -0.3528113, -0.3528113,
        -0.3528113],
       [-0.3528113, -0.3528113, -0.3528113, ..., -0.3528113, -0.3528113,
        -0.3528113],
       [-0.3528113, -0.3528113, -0.3528113, ..., -0.3528113, -0.3528113,
        -0.3528113],
       ...,
       [-0.3528113, -0.3528113, -0.3528113, ..., -0.3528113, -0.3528113,
        -0.3528113],
       [-0.3528113, -0.3528113, -0.3528113, ..., -0.3528113, -0.3528113,
        -0.3528113],
       [-0.3528113, -0.3528113, -0.3528113, ..., -0.3528113, -0.3528113,
        -0.3528113]], dtype=float32)

In [0]:
X_test -= mean

In [0]:
X_test

array([[-0.3528113 , -0.3528113 , -0.3528113 , ..., -0.3528113 ,
        -0.3528113 , -0.3528113 ],
       [-0.3528113 , -0.3528113 , -0.3528113 , ..., -0.3528113 ,
        -0.3528113 , -0.3528113 ],
       [-0.3528113 , -0.3528113 , -0.3528113 , ..., -0.3528113 ,
        -0.3528113 , -0.3528113 ],
       ...,
       [-0.3528113 , -0.3528113 , -0.3528113 , ..., -0.3528113 ,
        -0.34888974, -0.3528113 ],
       [-0.3528113 , -0.34888974, -0.3410466 , ..., -0.3528113 ,
        -0.3528113 , -0.3528113 ],
       [-0.3528113 , -0.3528113 , -0.3528113 , ..., -0.3528113 ,
        -0.3528113 , -0.3528113 ]], dtype=float32)

In [0]:
input_dim = X_train.shape[1]

In [0]:
input_dim

784

In [0]:
nb_classes = y_train.shape[1]

In [0]:
nb_classes

10

**Agora vamos aplicar uma MLP**

In [0]:
model = Sequential()

In [0]:
model

In [0]:
model.add(Dense(128, input_dim=input_dim))

In [0]:
model.add(Activation('relu'))

In [0]:
model.add(Dropout(0.15))

In [0]:
model.add(Dense(128))

In [0]:
model.add(Activation('relu'))

In [0]:
model.add(Dropout(0.15))

In [0]:
model.add(Dense(nb_classes))

In [0]:
model.add(Activation('softmax'))

**Usaremos o <em>categorical_crossentropy</em> para a perda e <em>rmsprop</em> como otimizador**

In [0]:
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

In [0]:
print('Treinando...')
model.fit(X_train, y_train, epochs=10, batch_size=16, validation_split=0.1, verbose=2)
print('Pronto!')

Treinando...
Train on 54000 samples, validate on 6000 samples
Epoch 1/10
 - 10s - loss: 0.5447 - val_loss: 0.4857
Epoch 2/10
 - 11s - loss: 0.4821 - val_loss: 0.4679
Epoch 3/10
 - 10s - loss: 0.5006 - val_loss: 0.4554
Epoch 4/10
 - 10s - loss: 0.5075 - val_loss: 0.5229
Epoch 5/10
 - 10s - loss: 0.5290 - val_loss: 0.4946
Epoch 6/10
 - 10s - loss: 0.5456 - val_loss: 0.5188
Epoch 7/10
 - 10s - loss: 0.5549 - val_loss: 0.5455
Epoch 8/10
 - 10s - loss: 0.5606 - val_loss: 0.5069
Epoch 9/10
 - 10s - loss: 0.5730 - val_loss: 0.5893
Epoch 10/10
 - 10s - loss: 0.5910 - val_loss: 0.5030
Pronto!


In [0]:
model.evaluate(X_train, y_train, verbose=0)

0.3948550893306732

In [0]:
print('Gerando as predições de teste...')
preds = model.predict_classes(X_test, verbose=0)

Gerando as predições de teste...


In [0]:
preds

array([0, 1, 2, ..., 8, 8, 1])

In [0]:
pd.DataFrame({"ImageId": list(range(1, len(preds)+1)), "Label": preds}) #.to_csv(fname, index=False, header=True)

ImageId  Label
0           1      0
1           2      1
2           3      2
3           4      2
4           5      3
...       ...    ...
9995     9996      0
9996     9997      6
9997     9998      8
9998     9999      8
9999    10000      1

[10000 rows x 2 columns]